# common
model_name: QCNet

# model
dataset: "argoverse_v2"
input_dim: 2
hidden_dim: 128
output_dim: 2
output_head: false
num_historical_steps: 50 #20
num_future_steps: 60 #30
num_modes: 6
num_recurrent_steps: 3
num_freq_bands: 64
num_map_layers: 1
num_agent_layers: 2
num_dec_layers: 2
num_heads: 8
head_dim: 16
dropout: 0.1
pl2pl_radius: 150
time_span: 10
pl2a_radius: 50
a2a_radius: 50
num_t2m_steps: 30
pl2m_radius: 150
a2m_radius: 150
# lr: 0.0005
# weight_decay: 0.0001
T_max: 64
submission_dir: "./"
submission_file_name: "submission"

train_batch_size: 1
val_batch_size: 1
test_batch_size: 1
# devices: [0]

# train
max_epochs: 128
learning_rate: 0.0001
learning_rate_sched: [ 10, 20, 30, 40, 50 ]
optimizer: AdamW
scheduler: lambdaLR
grad_clip_norm: 1000.0
weight_decay: 0.01
# lr_decay: 0.5
# lr_clip: 0.000001
# train_batch_size: 256 #32 #128
eval_batch_size: 2 #32 #128

# data related
max_num_agents: 64
map_range: 100
max_num_roads: 768
max_points_per_lane: 30 # will be overwritten if manually_split_lane is True
manually_split_lane: False
input_keys: [
  'heading',
  'category',
  'edge_index',
  'batch',
  'type',
  'num_nodes',
  'valid_mask',
  'scenario_id',
  'magnitude',
  'side',
  'orientation',
  'position',
  'id',
  'height',
  'velocity',
  'ptr',
  'predict_mask',
  'target',
  'is_intersection',
  'av_index',
  'city'
  ]
